server:
  port: 8082
  servlet:
    context-path: /games

spring:
  application:
    name: games
  datasource:
    url: jdbc:mysql://localhost:3306/game-service
    username: root
    password: thienhuu2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "games"
    description: "VOU-Final games service"
    version: "1.0.0"