server:
  port: 8087

spring:
  application:
    name: gift-service
  datasource:
    url: jdbc:postgresql://localhost:5435/giftdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

cloudinary:
  cloud-name: dzxmtqqdy
  api-key: 277899743332743
  api-secret: qdXbGaSvk4GbAxuNpB4b-F5mBl0