server:
  port: 8083

spring:
  application:
    name: event-service

  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5434/eventdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

cloudinary:
  cloud-name: dzxmtqqdy
  api-key: 277899743332743
  api-secret: qdXbGaSvk4GbAxuNpB4b-F5mBl0